name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      # Checkout code with write permissions
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Full history for accurate diffs

      # Set up PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, mysql

      # Cache Composer dependencies
      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-vendor-

      # Install dependencies
      - name: Install Dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        env:
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1

      # Cache Pint
      - name: Cache Pint
        uses: actions/cache@v4
        with:
          path: ./storage/pint.cache
          key: ${{ runner.os }}-pint-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-pint-

      # Run Laravel Pint
      - name: Run Pint
        run: ./vendor/bin/pint --dirty

      # Cache Rector
      - name: Cache Rector
        uses: actions/cache@v4
        with:
          path: ./storage/rector
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-rector-

      # Run Rector
      - name: Run Rector
        run: vendor/bin/rector process --ansi

      # Cache Larastan
      - name: Cache Larastan
        uses: actions/cache@v4
        with:
          path: .phpstan.cache
          key: ${{ runner.os }}-phpstan-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-phpstan-

      # Run Larastan
      - name: Run Larastan
        run: vendor/bin/phpstan analyse -c phpstan.neon

      # Commit changes from Pint and Rector
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[CI] Apply Pint and Rector fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'
          commit_user_name: 'github-actions[bot]'
          file_pattern: '*.php' # Only commit PHP files
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: false
          disable_globbing: false
          create_branch: false
        env:
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1